/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppAdd {
    'getArt': (id: any) => Promise<void>;
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppArticleCard {
    'article': any;
  }
  interface AppArticleCardAttributes extends StencilHTMLAttributes {
    'article'?: any;
  }

  interface AppArticle {
    'match': MatchResults;
  }
  interface AppArticleAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppArticles {
    'articles': any;
  }
  interface AppArticlesAttributes extends StencilHTMLAttributes {
    'articles'?: any;
  }

  interface AppConfirm {
    'componentWillLoad': () => void;
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppConfirmAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppHome {
    'render': () => any;
  }
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppAdd': Components.AppAdd;
    'AppArticleCard': Components.AppArticleCard;
    'AppArticle': Components.AppArticle;
    'AppArticles': Components.AppArticles;
    'AppConfirm': Components.AppConfirm;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-add': Components.AppAddAttributes;
    'app-article-card': Components.AppArticleCardAttributes;
    'app-article': Components.AppArticleAttributes;
    'app-articles': Components.AppArticlesAttributes;
    'app-confirm': Components.AppConfirmAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppAddElement extends Components.AppAdd, HTMLStencilElement {}
  var HTMLAppAddElement: {
    prototype: HTMLAppAddElement;
    new (): HTMLAppAddElement;
  };

  interface HTMLAppArticleCardElement extends Components.AppArticleCard, HTMLStencilElement {}
  var HTMLAppArticleCardElement: {
    prototype: HTMLAppArticleCardElement;
    new (): HTMLAppArticleCardElement;
  };

  interface HTMLAppArticleElement extends Components.AppArticle, HTMLStencilElement {}
  var HTMLAppArticleElement: {
    prototype: HTMLAppArticleElement;
    new (): HTMLAppArticleElement;
  };

  interface HTMLAppArticlesElement extends Components.AppArticles, HTMLStencilElement {}
  var HTMLAppArticlesElement: {
    prototype: HTMLAppArticlesElement;
    new (): HTMLAppArticlesElement;
  };

  interface HTMLAppConfirmElement extends Components.AppConfirm, HTMLStencilElement {}
  var HTMLAppConfirmElement: {
    prototype: HTMLAppConfirmElement;
    new (): HTMLAppConfirmElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-add': HTMLAppAddElement
    'app-article-card': HTMLAppArticleCardElement
    'app-article': HTMLAppArticleElement
    'app-articles': HTMLAppArticlesElement
    'app-confirm': HTMLAppConfirmElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-add': HTMLAppAddElement;
    'app-article-card': HTMLAppArticleCardElement;
    'app-article': HTMLAppArticleElement;
    'app-articles': HTMLAppArticlesElement;
    'app-confirm': HTMLAppConfirmElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
